InterestShare.Management/Models/MenuGroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterestShare.Management.Models
{
    /// <summary>
    /// 菜单组别视图模型
    /// </summary>
    public class MenuGroupViewModel
    {
        /// <summary>
        /// 分组ID
        /// </summary>
        public int GroupID { get; set; }

        /// <summary>
        /// 分组名称
        /// </summary>
        public string GroupName { get; set; }
    }
}

InterestShare.Management/Models/MenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterestShare.Management.Models
{
    public class MenuViewModel
    {

        public int MenuGroupID { get; set; }
        public string MenuName { get; set; }

        public string MenuID { get; set; }

        public string Url { get; set; }

        public int Sort { get; set; }

    }
}

InterestShare.Management/Models/SystemModels/AjaxViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InterestShare.Management.Models.SystemModels
{
    public class AjaxViewModel
    {
        public AjaxViewModel()
        {
            this.isSuccess = false;
        }

        public bool isSuccess { get; set; }

        public string message { get; set; }

        public static AjaxViewModel Success()
        {
            return new AjaxViewModel { isSuccess = true };
        }
    }

    public class AjaxViewModel<T> : AjaxViewModel where T : class
    {
        public T obj { get; set; }
    }
}

InterestShare.Management/Controllers/AccountController.cs
using InterestShare.Bll;
using InterestShare.Bll.Bll;
using InterestShare.Bll.IBll;
using InterestShare.Model.Models;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace InterestShare.Management.Controllers
{
    public class AccountController : Controller
    {

        public AccountController()
        {


        }
        private IAuthenticationManager Authentication
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }
        protected IUserBll userbll
        {
            get
            {
                return BllFactory.GetBLLInstance<UserBll>();
            }
        }
        public ActionResult Login()
        {

            return View();
        }

        public ActionResult DoLogin(string name, string password)
        {
            //"nqz", "nqz"
            User model = userbll.Query(name,password);
            if (model != null && !string.IsNullOrEmpty(model.Account))
            {
                SignIn(name);
                return Redirect("/Home/Index");
            }
            else
            {
                return View("Login", new { tip = "用户名或密码错误" });
            }
        }

        private void SignIn(string name)
        {
            var identity = new ClaimsIdentity(
             new[] { new Claim(ClaimTypes.Name, name) },
             DefaultAuthenticationTypes.ApplicationCookie,
             ClaimTypes.Name, ClaimTypes.Role);
            Authentication.SignIn(new AuthenticationProperties
            {
                IsPersistent = false
            }, identity);
        }

        public ActionResult Exit()
        {
            Authentication.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return View("Login");
        }
    }
    }

InterestShare.Management/Controllers/HomeController.cs
using InterestShare.Management.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InterestShare.Management.Controllers
{
    [Authorize]
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult IndexMenuView()
        {
            var MenuGroup = GetMenuGroup();
            var MenuDetails = GetMenuDetailList();
            ViewData["MenuGroup"] = MenuGroup;
            ViewData["MenuDetails"] = MenuDetails;
            return PartialView("Index_MenuListPartial");
        }
    }
}

InterestShare.Management/Controllers/ResourceController.cs
using InterestShare.Bll;
using InterestShare.Bll.Bll;
using InterestShare.Bll.IBll;
using InterestShare.Management.Core;
using InterestShare.Management.Models.SystemModels;
using InterestShare.Model;
using InterestShare.Model.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InterestShare.Management.Controllers
{
        public class ResourceController : BaseController
        {

            protected IResourceBll ResourceBll
            {
                get
                {
                    return BllFactory.GetBLLInstance<ResourceBll>();
                }
            }
            /// <summary>
            /// 业务系统主页
            /// </summary>
            /// <returns></returns>
            public ActionResult ResourceIndex()
            {
                return View();
            }

            /// <summary>
            /// 分页查询
            /// </summary>
            /// <param name="page"></param>
            /// <param name="rows"></param>
            /// <param name="name">业务系统名称</param>
            /// <param name="code">业务系统编码</param>
            /// <returns></returns>
            public ActionResult GetDataGridDataByCondition(int page, int rows, string name, string code)
            {
                AjaxViewModel<CommonPagedDataViewModel<ResourceModel>> result = new AjaxViewModel<CommonPagedDataViewModel<ResourceModel>>();
                try
                {
                    CommonPagedDataViewModel<ResourceModel> data = ResourceBll.GetResourceByCondition(page, rows, name, code);
                    result = new AjaxViewModel<CommonPagedDataViewModel<ResourceModel>>
                    {
                        isSuccess = true,
                        obj = data
                    };
                }
                catch (Exception ex)
                {

                }
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            /// <summary>
            /// 添加或者修改业务系统
            /// </summary>
            /// <param name="model"></param>
            /// <returns></returns>
            public ActionResult AddOrEditResource(long id = 0)
            {
                ResourceModel model = new ResourceModel();
                if (id > 0)
                {
                    //添加业务系统
                    model = ResourceBll.GetResourceById(id);
                }
                return View(model);
            }

            /// <summary>
            /// 插入业务系统
            /// </summary>
            /// <param name="model"></param>
            /// <returns></returns>
            public JsonResult UpdateResource(ResourceModel model)
            {

                int result = ResourceBll.InsertResource(model);
                if (result > 0)
                {
                    return Json(new AjaxViewModel
                    {
                        isSuccess = true
                    });
                }
                return Json(new AjaxViewModel
                {
                    isSuccess = false
                });
            }

            /// <summary>
            /// 插入业务系统
            /// </summary>
            /// <param name="model"></param>
            /// <returns></returns>
            public int DeleteResource(long id)
            {
                return ResourceBll.DeleteResource(id);
            }
        }
    }

InterestShare.Management/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

InterestShare.Management/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

InterestShare.Management/Views/Home/Index.cshtml
@{
    Layout = null;
    var version = 1.0;
}

<!DOCTYPE html>
<html>
<head>
    <title>电影资源共享管理平台</title>
    <meta charset="utf-8" />

    <link id="easyuiTheme" rel="stylesheet" href="~/Scripts/jquery-easyui-1.3.5/themes/default/easyui.css?v=@version" type="text/css">
    <link href="/Content/default.css?v=@version" rel="stylesheet" />
    <link href="/Content/site.css?v=@version" rel="stylesheet" />
    <link href="/Content/icon.css?v=@version" rel="stylesheet" />
    <link href="~/Content/KindEditor/themes/default/default.css?v=@version" rel="stylesheet" />
    <link href="~/Content/Style/hotel.less?v=@version" rel="stylesheet" />

    <script src="/Scripts/jquery-1.8.2.js?v=@version"></script>
    <script src="/Scripts/jquery-extents.js?v=@version"></script>

    <script src="/Scripts/jquery-easyui-1.3.5/jquery.easyui.js?v=@version"></script>
    <script src="/Scripts/jquery-easyui-1.3.5/locale/easyui-lang-zh_CN.js?v=@version"></script>
    <script src="/Scripts/jquery-easyui-1.3.5/jquery.easyui-extents.js?v=@version"></script>

    <script src="/Scripts/jquery.json-2.4.js?v=@version"></script>

    <script src="~/Content/KindEditor/kindeditor.js?v=@version"></script>
    <script src="~/Content/KindEditor/plugins/image/image.js?v=@version"></script>
    <script src="~/Content/KindEditor/lang/zh_CN.js?v=@version"></script>

    <script src="~/Content/My97DatePicker/WdatePicker.js?v=@version"></script>
    <script>
        var esuiDialog = $.fn.dialog;
    </script>
    <script src="~/scripts/lhgdialog/lhgdialog.min.js?v=@version"></script>
    <script>
        $.fn.LhgDialog = $.fn.dialog;
        $.fn.dialog = esuiDialog;
    </script>

    <link href="~/Content/webuploader-0.1.5/webuploader.css?v=@version" rel="stylesheet" />
    <script src="~/Content/webuploader-0.1.5/webuploader.js?v=@version"></script>

    <link href="~/Content/FullCalendar-1.5.4/fullcalendar.css?v=@version" rel="stylesheet" />
    <link href="~/Content/FullCalendar-1.5.4/fullcalendar.print.css?v=@version" rel="stylesheet" />
    <script src="~/Content/FullCalendar-1.5.4/fullcalendar.min.js?v=@version"></script>

    <script src="~/Content/Javascript/common_fn.js?v=@version"></script>
    <script src="~/Content/PageModule/System/global.js?v=@version"></script>
    <script src="~/Content/PageModule/System/home.index.js?v=@version"></script>
    <script src="~/Content/Javascript/jquery.selectpicture.js?v=@version"></script>
    <script type="text/javascript">
        var logoutPostUrl = '@Url.Action("Exit", "Account")';
        var loginUrl = '@Url.Action("Login", "Account")';
        var systemBaseUrl = '@Url.Content("~/").TrimEnd('/')';
        var $captchaBaseUrl = '@Url.Action("Captcha", "Common")';
        var $reloginViewUrl = '@Url.Action("GetReloginView", "Account")';
        var $modifyPasswordViewUrl = '@Url.Action("GetModifyPasswordView", "Account")';
    </script>

    <script type="text/javascript">
        var kindeditor;
        KindEditor.ready(function (K) {
            kindeditor = K;
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $(document).keydown(function (e) {
                var keycode = window.event ? e.keyCode : e.which;
                var ev = e || window.event;
                var obj = ev.target || ev.srcElment;
                var t = obj.type || obj.getAttribute('type');
                if (event.keyCode == 8) {
                    if (t == "password" || t == "text" || t == "textarea") {
                        if (document.activeElement.readOnly == false)
                            return true;
                    }
                    return false;
                }
            });
        });
    </script>
</head>
<body class="easyui-layout">
    <noscript>
        <div style="position: absolute; z-index: 100000; height: 2046px; top: 0px; left: 0px;width: 100%; background: white; text-align: center;">
            <img src="/content/images/noscript.gif" alt='抱歉，请开启脚本支持！' />
        </div>
    </noscript>


    <div data-options="region:'north',border:false" style="height: 60px;line-height:60px;
    background-color: #E0ECFF;
    background: linear-gradient(to right,#EFF5FF 20%,skyblue 70%);
    background-repeat: repeat-x;  padding:10px;padding-left:20px; font:15px bold; font-family:黑体">
        @Html.Partial("Index_TopPartial")
    </div>

    <div data-options="region:'south',border:false" style="overflow: hidden">
        @Html.Partial("Index_BottomPartial")
    </div>



    <div data-options="region:'west',split:true,title:'功能导航',iconCls:'icon-home', href:'@Url.Action("IndexMenuView","Home")', onLoad: onMenuListLoad, loadingMessage:'正在加载...',tools:[{iconCls:'icon-refresh', handler:refreshMenuList }]" style="width: 250px;">
    </div>

    <div data-options="region:'center'" style="overflow: hidden;">
        <div id="index_tabs" style="overflow: hidden;">
            <div title="欢迎" data-options="border:false,iconCls:'icon-home'" style="overflow: hidden;">

                <div class="gjbody">
                    <div class="gjfrm">
                        @(new HtmlString(ViewBag.StrMap))
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="index_tabsMenu" style="width: 120px; display: none;">
        <div title="refresh" data-options="iconCls:'icon-reload'">刷新页面</div>
        <div class="menu-sep"></div>
        <div title="close" data-options="iconCls:'icon-close'">关闭当前</div>
        <div title="closeOther" data-options="iconCls:'icon-close-all'">关闭其他</div>
        <div title="closeAll" data-options="iconCls:'icon-close-all'">关闭所有</div>
    </div>


</body>
</html>
<style>
    .cls {
        width: 0;
        height: 0;
        overflow: hidden;
        clear: both;
    }

    .gjbody {
        /*background:url(../Content/Images/bg1.jpg) left top no-repeat #ebf2f9;*/
    }

    .gjfrm {
        width: 1013px;
        margin: 0 auto;
    }

    .gjtitle {
        width: 1013px;
        margin: 0 auto;
        font-weight: bold;
        font-size: 36px;
        font-family: "微软雅黑";
        color: #000;
        line-height: 1.5;
        padding-top: 30px;
        margin-bottom: 40px;
    }

        .gjtitle span {
            color: #378b02;
            font-size: 40px;
            font-family: "宋体";
        }

    .fc-event-hori {
        border-width: 0 0 0px 0 !important;
    }
</style>

InterestShare.Management/Views/Home/Index_BottomPartial.cshtml
<div class="panel-header panel-title" style="text-align: center;border:0px">
    Copyright &copy; 陌上桑智
</div>

InterestShare.Management/Views/Home/Index_MenuListPartial.cshtml
<div class="easyui-accordion" data-options="fit:true,border:false">

    @{
        var groupIds = ViewData["MenuGroup"] as List<InterestShare.Management.Models.MenuGroupViewModel>;
        var menuDetails = ViewData["MenuDetails"] as List<InterestShare.Management.Models.MenuViewModel>;
    }

    @if (groupIds != null)
    {
        foreach (var groupitem in groupIds)
        {
            <div title="@groupitem.GroupName" data-options="border:false,iconCls:'icon-folder'" class="left-menus">
                @{
                    var menus = menuDetails.Where(x => x.MenuGroupID == groupitem.GroupID).OrderBy(x => x.Sort).ToList();
                    foreach (var menu in menus)
                    {
                        <div class="tree-node" style="cursor: pointer;">
                            <span class="icon-ok" style="width:16px;height:16px; display:inline-block;vertical-align:middle;"></span>
                            <span class="tree-title">@menu.MenuName</span>
                            <span class="href" style="display: none;">@menu.Url</span>
                        </div>
                    }
                }
            </div>
                        }
                    }
</div>

InterestShare.Management/Views/Home/Index_TopPartial.cshtml
<div style="position: absolute; right: 0px; bottom: 0px;">
    <a href="javascript:void(0);" class="easyui-menubutton" data-options="menu:'#layout_north_kzmbMenu',iconCls:'icon-config'" style="color:black">控制面板</a>
    <a href="javascript:void(0);" class="easyui-menubutton" data-options="menu:'#layout_north_pfMenu',iconCls:'icon-key'">更换皮肤</a>
</div>

<div id="layout_north_pfMenu" style="width: 120px; display: none;">
    <div onclick="changeTheme('default');" title="default">default</div>
    <div onclick="changeTheme('gray');" title="gray">gray</div>
    <div onclick="changeTheme('bootstrap');" title="bootstrap">bootstrap</div>
    <div onclick="changeTheme('metro');" title="metro">metro</div>
    <div onclick="changeTheme('metro-blue');" title="metro-blue">metro-blue</div>
    <div onclick="changeTheme('metro-gray');" title="metro-gray">metro-gray</div>
    <div onclick="changeTheme('metro-green');" title="metro-green">metro-green</div>
    <div onclick="changeTheme('metro-orange');" title="metro-orange">metro-orange</div>
    <div onclick="changeTheme('metro-red');" title="metro-red">metro-red</div>
</div>
<div id="layout_north_kzmbMenu" style="width: 100px; display: none;">

    <div onclick="exitSystem();" data-options="iconCls:'icon-redo'">退出系统</div>

</div>

@*<div style="float:left;height:38px;width:415px; background-image:url(../../Content/Image/logo_menu.png)"></div>*@
<div style="position: absolute; right: 5px; top: 10px; font-size:13px;" id="div_welcom">
    @*<div id="loginName" style="display:none">
        <span>@helpers.sessions(x => x.LoginUserName)</span></div>
        &nbsp;姓名:<span>@helpers.sessions(x => x.LoginName) </span>
        &nbsp;帐号:<span>@helpers.sessions(x => x.LoginUserName)</span>
        &nbsp;角色:<span>@helpers.sessions(x => x.RoleName) </span>*@
</div>

InterestShare.Management/Views/Resource/AddOrEditResource.cshtml
@model  InterestShare.Model.Models.ResourceModel
@{
    ViewBag.Title = "AddOrEditResource";
}
<style>
    .linkCSS {
        width:500px;
    }
    input, select, textarea {
        max-width:500px;
    }
</style>
<div class="easyui-layout" data-options="fit:true,border:false" style="height:300px">
    <div data-options="region:'center',border:false" title="" style="overflow: hidden;">
        <form id="form_BusinesSystem" method="post" action="/Resource/UpdateResource" class="form-horizontal" style="height:626px;overflow-y:scroll;overflow-x:hidden;">
            @Html.HiddenFor(x => x.ID)
            <table class="tableForm" style="width: 100%">
                <tr>
                    <td>资源名称：</td>
                    <td>
                        @Html.TextBoxFor(x => x.ResourceName, new { @class = "easyui-validatebox", data_options = "required:true", maxlength = 100 })
                    </td>
                </tr>
                <tr>
                    <td>资源提取码：</td>
                    <td>
                        @Html.TextBoxFor(x => x.ResourcePassword, new { @class = "easyui-validatebox", data_options = "required:true", maxlength = 100 })
                    </td>
                </tr>
                <tr>
                    <td>资源链接：</td>
                    <td>
                        @Html.TextBoxFor(x => x.ResourceLink, new { @class = "easyui-validatebox linkCSS", data_options = "required:false", maxlength = 300 })
                    </td>
                </tr>
                <tr>
                    <td>资源图片路径：</td>
                    <td>
                        @Html.TextBoxFor(x => x.ResourceImg, new { @class = "easyui-validatebox linkCSS", data_options = "required:false", maxlength = 300 })
                    </td>
                </tr>
                <tr>
                    <td>备注：</td>
                    <td>
                        @Html.TextBoxFor(x => x.Remark, new { @class = "easyui-validatebox", data_options = "required:false", maxlength = 100 })
                    </td>
                </tr>
                <tr>
                    <td>是否启用</td>
                    <td>
                        <div>
                            <label>
                                @Html.RadioButtonFor(model => model.IsEnable, true, new { @checked = true }) <span>启用 </span>
                                @Html.RadioButtonFor(model => model.IsEnable, false, new { }) <span>不启用</span>
                            </label>
                        </div>
                    </td>
                </tr>

            </table>

        </form>
    </div>
</div>

<script type="text/javascript">

    $(function () {
        $('#form_BusinesSystem').form({
            url: '@Url.Action("UpdateResource", "Resource")',
            onSubmit: function () {
                parent.$.messager.progress({
                    title: '提示',
                    text: '数据处理中，请稍后...'
                });
                var isValid = $(this).form('validate');
                if ($.trim($("#ResourceName").val()) == '') {
                    isValid = false;
                    messager.info("提示", "资源名称不能全为空格！");
                }
                if (!isValid) {
                    parent.$.messager.progress('close');
                }
                return isValid;
            },
            success: function (data) {
                parent.$.messager.progress('close');
                data = $.parseJSON(data);
                if (data.isSuccess) {
                    messager.info("提示", "保存成功！", parent.$.modalDialog.openner_dataGrid.reload);
                    parent.$.modalDialog.handler.dialog('close');
                } else {
                    parent.$.messager.alert('错误', "保存失败，可能的原因：业务平台编码不能重复", 'error');
                }
            }

        });
        parent.$.messager.progress('close');
    });

</script>

InterestShare.Management/Views/Resource/ResourceIndex.cshtml
@{
    ViewBag.Title = "ResourceIndex";
}

@section scripts{
    <script type="text/javascript">
        var grid = new DataGrid();

        $(function () {

            InitDataGrid($('#ResourceCheck').val(), $('#ResourceCodeCheck').val());

            $('#btn_Query').click(function () {
                InitDataGrid($('#ResourceCheck').val(), $('#ResourceCodeCheck').val());
            })

        });

        function InitDataGrid(ResourceCheck, ResourceCodeCheck) {
            grid = new DataGrid("#dataGrid", {
                url: "/Resource/GetDataGridDataByCondition",
                method: "GET",
                queryParams: {
                    name: ResourceCheck,
                    code: ResourceCodeCheck,
                },
                columns: [
                     {
                         field: 'ID',
                         title: 'ID',
                         width: 50,
                         checkbox: true
                     },
                    {
                        field: 'ResourceName',
                        title: '资源名称',
                        width: 100,
                    },
                    {
                        field: 'ResourcePassword',
                        title: '资源提取码',
                        width: 200
                    },
                    {
                        field: 'ResourceLink',
                        title: '资源下载链接',
                        width: 200
                    },
                     {
                         field: 'ResourceImg',
                         title: '图片路径',
                         width: 200
                     },
                    {
                        field: 'IsEnable',
                        title: '是否启用',
                        width: 200
                    },
                 {
                     field: 'Remark',
                     title: '备注',
                     width: 200
                 },

                ],
                toolbar: "#toolbar",
                onDblClickRow: function (rowIndex, rowData) {
                    return edit(rowData.ID);
                },
                loadFilter: function (data) {
                    if (data.isSuccess) {
                        return {
                            rows: data.obj.Items,
                            total: data.obj.TotalNum
                        };
                    }
                },
            });

        }

        function newIframe(url, title) {
            parent.newIframe(url, title);
        }

        function refresh() {
            grid.reload();
        };

        function edit(id) {
            if (id) {
                grid.selectRecord(id);
            }

            var row = grid.getCheckedRow();
            if (!row) {
                return;
            }
            showEditView(row.ID, "修改资源 ");
        };

        function add() {
            showEditView(null, "添加资源");
        };

        function showEditView(id, title) {
            var param;
            var winWidth = $(window.top).width();
            var popHeight = winWidth < 1440 ? 600 : 800;
            if (id) {
                param = "?id=" + id;
            }
            var href = "/Resource/AddOrEditResource";
            parent.$.modalDialog.openner_dataGrid = grid;
            parent.$.modalDialog({
                title: title,
                width: 660,
                height: 300,
                href: href + (param || ""),
                buttons: [
                  {
                      text: '确定',
                      iconCls: 'icon-save',
                      handler: function () {
                          //var sentdata = { ID: $("#ID").val(), Resource: $("#Resource").val(), ResourceCode: $("#ResourceCode").val(), Remark: $("#Remark").val(), IsEnable: $("#IsEnable:checked").val(),
                          //    PrefixCode: $("#PrefixCode").val()
                          //};
                          //$.ajax({
                          //    type: "POST",
                          //    url: "/Resource/UpdateResource",
                          //    data: sentdata,
                          //    success: function (data) {
                          //        if (data > 0) {
                          //            messager.info("提示", "保存成功！", grid.reload);
                          //            return parent.$.modalDialog.handler.dialog('close');
                          //        }
                          //        else {
                          //            messager.info("提示", "保存失败！");
                          //        }
                          //    }
                          //});

                          var frm;
                          frm = parent.$.modalDialog.handler.find('#form_BusinesSystem');
                          console.log(frm);
                          if (frm) {
                              return frm.submit();
                          }

                      }
                  }, {
                      text: '取消',
                      iconCls: 'icon-cancel',
                      handler: function () {
                          return parent.$.modalDialog.handler.dialog('close');
                      }
                  }
                ],
                onLoad: function () {
                    var $form = parent.$.modalDialog.handler.find('#form');
                    utils.wrapForm($form, "", function (record) {
                        if (!record.IsSuccess) {
                            messager.info('提示', record.Message, grid.reload);
                        }
                        else {
                            messager.info("提示", "保存成功！", grid.reload);
                        }
                    });
                }
            });
        }

        function del(id) {
            if (id) {
                grid.selectRecord(id);
            }

            var row = grid.getCheckedRow();
            if (!row) {
                return;
            }
            var deleteUrl = "/Resource/DeleteResource";
            $.messager.confirm("提示", "你确定要删除吗", function (result) {
                if (result) {
                    $.post(deleteUrl, { id: row.ID }, function (response) {
                        if (response > 0) {
                            grid.reload();
                        }
                        else {
                            messager.error("错误", response);
                        }

                        messager.progress.hide();
                    });
                }
            });
        };

        function clearSelections() {
            grid.clearSelections();
        }
    </script>
}

<div class="easyui-layout" data-options="fit:true,border:false">
    <div data-options="region:'north',border:false" class="search-bar">
        <table>
            <tr>
                <td class="label">资源名称：</td>
                <td class="control">
                    <input type="text" id="ResourceCheck" class="easyui-validatebox" />
                </td>
                <td>
                    <a href="javascript:void(0);" id="btn_Query" class="easyui-linkbutton" data-options="iconCls:'icon-ok'">查询</a>
                </td>
            </tr>
        </table>
    </div>
    <div data-options="region:'center',border:false">
        <table id="dataGrid"></table>
    </div>
</div>
<div id="toolbar">
    <table>
        <tr>
            <td>
                <a onclick="add();" href="javascript:void(0);" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-add'">添加</a>
            </td>
            <td>
                <div class="datagrid-btn-separator"></div>
            </td>
            <td>
                <a onclick="edit();" href="javascript:void(0);" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-edit'">修改</a>
            </td>
            <td>
                <div class="datagrid-btn-separator"></div>
            </td>
            <td>
                <a onclick="refresh();" href="javascript:void(0);" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-reload'">刷新</a>
            </td>
            <td>
                <a onclick="clearSelections();" href="javascript:void(0);" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-undo'">取消选择</a>
            </td>
            <td>
                <a onclick="del();" href="javascript:void(0);" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-remove'">删除</a>
            </td>
            <td></td>
        </tr>
    </table>
</div>

<!--右键菜单-->
<div id="menu" class="easyui-menu" style="width: 120px; display: none;">
    <div onclick="edit();" data-options="iconCls:'icon-edit'">修改</div>
    <div onclick="del();" data-options="iconCls:'icon-remove'">删除</div>
    <div onclick="add();" data-options="iconCls:'icon-add'">添加</div>
    <div class="menu-sep"></div>
    <div onclick="refresh();" data-options="iconCls:'icon-reload'">刷新</div>
</div>